name              = "service-mesh-at-scale"
tfc_organization  = "hashicorp-team-demo"
tfc_project       = "service-mesh-at-scale"
github_repository = "jcolemorrison/service-mesh-at-scale"
github_branch     = "gcp-services"